### ISSUE TITLE
` Error: Nock: No match for request ` when CMS_URL enabled in .env 

### ISSUE THREAD

**Issue by starsinmypockets** [datopian/frontend-v2#3]
Steps to reproduce:
1. `mv template.env .env`
2. Update `CMS_URL` in `.env`
3. `yarn start`

Error:
```
(node:16608) UnhandledPromiseRejectionWarning: Error: Nock: No match for request {
  "method": "GET",
  "url": "https://public-api.wordpress.com/rest/v1.1/sites/https%3A%2F%2Fedscms.home.blog/posts?number=10"
}
    at end (/home/pj/Datopian/repos/frontend-v2/node_modules/nock/lib/request_overrider.js:277:17)
    at /home/pj/Datopian/repos/frontend-v2/node_modules/nock/lib/request_overrider.js:160:9
    at OverriddenClientRequest.RequestOverrider.req.write (/home/pj/Datopian/repos/frontend-v2/node_modules/nock/lib/request_overrider.js:139:9)
    at OverriddenClientRequest.RequestOverrider.req.end (/home/pj/Datopian/repos/frontend-v2/node_modules/nock/lib/request_overrider.js:156:11)
    at Request._end (/home/pj/Datopian/repos/frontend-v2/node_modules/superagent/lib/node/index.js:1021:9)
    at Request.end (/home/pj/Datopian/repos/frontend-v2/node_modules/superagent/lib/node/index.js:777:15)
    at sendResponse (/home/pj/Datopian/repos/frontend-v2/node_modules/wpcom-xhr-request/build/index.js:67:6)
    at request (/home/pj/Datopian/repos/frontend-v2/node_modules/wpcom-xhr-request/build/index.js:226:2)
    at WPCOM.request (/home/pj/Datopian/repos/frontend-v2/node_modules/wpcom/build/index.js:121:41)
    at /home/pj/Datopian/repos/frontend-v2/node_modules/wpcom/build/lib/util/send-request.js:110:9
```

**Comment by anuveyatsu** [comment]
@starsinmypockets you probably mean `WP_URL`? I've missed saying in the README that you need to set `NODE_ENV` env var to something not equal to `development` to switch off the mocks.
